config/routes.rb
Rails.application.routes.draw do

  resources :categories
  get 'users/new'
  root to: "static_pages#home"

  get  '/about',   to: 'static_pages#about'
  get  '/contact',   to: 'static_pages#contact'

  devise_for :users
  resources :records do
    member do
      post 'update_status'
    end
  end
  resources :users
  # post "records/update_status" => "records#update_status"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :records, :dependent => :destroy
  belongs_to :user

  validates :title,
          :presence => {:message => "Title can't be blank." },
          :uniqueness => {:message => "Title already exists."},
          :length => { :maximum => 100, :message => "Must be less than 100 characters"}
end

app/models/record.rb
class Record < ApplicationRecord
  belongs_to :user
  belongs_to :category
  default_scope -> { order(due_date: :asc) }
  validates :user_id, presence: true
  after_create :set_status
  after_create :set_frequency


  validates :title,
          :presence => {:message => "Title can't be blank." },
          # :uniqueness => {:message => "Title already exists."},
          :length => { :maximum => 100, :message => "Must be less than 100 characters"}

  validates :content,
          :presence => {:message => "Content can't be blank." },
          :length => { :maximum => 200, :message => "Must be less than 200 characters"}

  validates :due_date,
          :presence => {:message => "Date can't be blank." }

  FREQUENCY = {'0': 'Every week',
                '1': 'Every month',
                '2': 'Every 3 months',
                '3': 'Every 6 months',
                '4': 'Every year'
              }

  STATUSES = {'0': 'No Action Required',
              '1': 'Action!',
              '2': 'Done',
              '3': 'Deleted'
              }

  def set_status
    self.update_attributes(status: 0)
  end

  def set_frequency
    self.update_attributes(frequency: 0)
  end

  def status_title
    STATUSES[status.to_s.to_sym]
  end

  def frequency_title
    FREQUENCY[frequency.to_s.to_sym]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :records, :dependent => :destroy
  has_many :categories
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = current_user.categories.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @categories = current_user.categories.find(params[:id])
  end

  # GET /categories/new
  def new
    @category = current_user.categories.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = current_user.categories.build(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to records_path, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to records_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = current_user.categories.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:record_id, :title, :user_id)
    end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action :authenticate_user!

  def show
    @record = current_user.records.find(params[:id])
  end

  def new
    @record = current_user.records.new
  end

  def index
    @records = current_user.records.all
  end

  def create
    @record = current_user.records.build(record_params)
    if @record.save
      redirect_to records_path
    else
    render action: "new"
    end
  end

  def update
    @record = current_user.records.find(params[:id])
    if @record.update_attributes(record_params)
      flash[:success] = "Record updated"
      redirect_to records_path
    else
      render 'edit'
    end
  end

  def destroy
    respond_to do |format|
      format.html { redirect_to records_url, notice: 'Record was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def update_status
    @record = current_user.records.find(params[:id])
    return if @record.status == 3
    if @record.update_attributes({status: (@record.status + 1)})
      flash[:success] = "Record updated"
      redirect_to records_path
    else
      render 'edit'
    end
  end

  private

  def record_params
    params.require(:record).permit(:title, :content, :frequency, :due_date, :category_id)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/records_helper.rb
module RecordsHelper

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_all_categories.html.erb
<br>
<div>
  <h4 class="brandColor">Current categories</h4>
</div>
<br>
  <% current_user.categories.all.each do |category| %>
   <div class="col s12 m6">
     <div class="card red darken-4">
       <div class="card-content white-text">
         <span class="card-title"><%= category.title %></span>
       </div>
       <div class="card-action">
         <div class="col s12 m6">
           <%= button_to "Edit", edit_category_path(category.id),
  :class => "waves-effect waves-light btn blue-grey darken-4
  ", :method => :get %>
          </div>
        <div class="col s12 m6">
         <%= button_to "Delete", category,
   :class => "waves-effect waves-light btn blue-grey darken-4
", :method => :delete, data: { confirm: 'Are you sure to delete this record?' } %>
        </div>
        <br>
        <br>
       </div>
     </div>
   </div>
 <% end %>

app/views/categories/_form.html.erb
<%= form_for(category) do |f| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<div class="row">
  <h1>Editing</h1>

  <%= render 'form', category: @category %>

  <%= link_to 'Show', @category %> |
  <%= link_to 'Back', categories_path %>
</div>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Record</th>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.title %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<div class="row">
<h1>New</h1>
<%= render 'form', category: @category %>

<%= button_to "Back", records_path,
:class => "waves-effect waves-light btn blue-grey darken-4 right-text
", :method => :get %>

<%= render 'all_categories' %>

</div>

app/views/categories/show.html.erb
  <div class="row z-depth-3" data-off-canvas-wrapper>
       <div class="col s12">
         <div class="card red darken-4">
           <div class="card-content white-text">
             <span class="card-title">Category: <%= @category.title %></span>
           </div>
           <div class="card-action">
             <div class="col s12 m4">
             <%= button_to "Back", records_path,
       :class => "waves-effect waves-light btn blue-grey darken-4
 ", :method => :get %>
             </div>
             <div class="col s12 m4">
             <%= button_to "Edit", edit_category_path(@category),
 :class => "waves-effect waves-light btn teal accent-4
 ", :method => :get %>
             </div>
             <div class="col s12 m4">
             <%= button_to "Delete", @category,
       :class => "waves-effect waves-light btn deep-orange accent-4
 ", :method => :delete, data: { confirm: 'Are you sure to delete this record?' } %>
             </div>
            <br>
            <br>
           </div>
         </div>
       </div>


    <div class="col s12 columns" data-off-canvas-content>
      <div class="title-bar hide-for-large">
        <div class="title-bar-left">
          <button class="menu-icon" type="button" data-open="my-info"></button>
        </div>
      </div>
      <div class="callout primary">
        <div class="row column">
          <% @category.records.each do |record| %>
            <div class="col s12 m6">
              <h3 class="header text-center"><%= record.title %></h3>
              <div class="card horizontal">
                <div class="card-image">
                  <!-- <img src="/assets/record-placeholder.jpeg"> -->
                </div>
                <div class="card-stacked">
                  <div class="card-content">
                    <p><%= record.content %></p>
                    <p>How often: <%= record.frequency %></p>
                    <p>Due Date: <%= record.due_date %></p>
                    <p>Category: <%= record.category.title %></p>
                  </div>
                  <div class="card-action">
                    <div class="col s12 m6">
                    <%= button_to "Edit", record_path(record.id),
        :class => "waves-effect waves-light btn blue-grey darken-4
        ", :method => :get %>
                    </div>
                    <div class="col s12 m6">
                    <%= button_to "Delete", record,
              :class => "waves-effect waves-light btn blue-grey darken-4
        ", :method => :delete, data: { confirm: 'Are you sure to delete this record?' } %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <% end %>
        </div>
        <%= link_to('Add new record', new_record_path) %>
      </div>
    </div>
  </div>

app/views/layouts/_copyright.html.erb
©2016 NZ Essential To-Do List

app/views/layouts/_footer.html.erb
<div class="row column">
  <ul class="menu">
    <li><a href="#">One</a></li>
    <li><a href="#">Two</a></li>
    <li><a href="#">Three</a></li>
    <li><a href="#">Four</a></li>
  </ul>
</div>

app/views/layouts/_header.html.erb
<div class="top-bar menu">
  <div class="top-bar-left">
    <ul class="menu">
      <li class="menu-text"><%= link_to('Home', root_path) %></li>
      <li><%= link_to('Dashboard', records_path) %></li>
    </ul>
  </div>
  <div class="top-bar-right">
    <ul class="menu">
      <% if user_signed_in? %>
        <li>
        <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
        </li>
      <% else %>
        <li>
        <%= link_to('Login', new_user_session_path)  %>
        </li>
      <% end %>
      <% if user_signed_in? %>
        <li>
        <%= link_to('Edit Profile', edit_user_registration_path) %>
        </li>
      <% else %>
        <li>
        <%= link_to('Register', new_user_registration_path)  %>
        </li>
      <% end %>
      <li><%= link_to "About", about_path %></li>
    </ul>
  </div>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!doctype html>
<html class="no-js" lang="en">
  <head>
    <title>EssentialApp</title>
    <%= csrf_meta_tags %>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Foundation | Welcome</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="http://dhbhdrzi4tiry.cloudfront.net/cdn/sites/foundation.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/css/materialize.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/js/materialize.min.js"></script>

    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <% if notice %>
    <div data-alert class="alert-box success radius text-center">
      <%= notice %>
      <a href="#" class="close">&times;</a>
    </div>

    <% end %>
    <% if alert %>
    <div data-alert class="alert-box warning radius text-center">
      <%= alert %>
      <a href="#" class="close">&times;</a>
    </div>
    <% end %>
    <%= yield %>
    <hr>
    <%= render 'layouts/footer' %>

    <div class="row copyright">
      <%= render 'layouts/copyright' %>
    </div>

    <script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
    <script src="http://dhbhdrzi4tiry.cloudfront.net/cdn/sites/foundation.js"></script>
    <script>
      $(document).foundation();
    </script>
  </body>
</html>

app/views/records/_all_categories.html.erb
<br>
<div>
  <%= link_to '+', new_category_path, :class => "btn-floating btn-large waves-effect waves-light red" %><span class="brandColor btn-text">Add new category</span>
</div>
<br>
  <% current_user.categories.all.each do |category| %>
   <div class="col s12 m6">
     <div class="card red darken-4">
       <div class="card-content white-text">
         <span class="card-title"><%= category.title %></span>
       </div>
       <div class="card-action">
         <div class="col s12 m6">
           <%= button_to "Edit", edit_category_path(category.id),
  :class => "waves-effect waves-light btn blue-grey darken-4
  ", :method => :get %>
          </div>
        <div class="col s12 m6">
         <%= button_to "Delete", category,
   :class => "waves-effect waves-light btn blue-grey darken-4
", :method => :delete, data: { confirm: 'Are you sure to delete this record?' } %>
        </div>
        <br>
        <br>
       </div>
     </div>
   </div>
 <% end %>

app/views/records/_all_records.html.erb
<br>
<div>
  <%= link_to '+', new_record_path, :class => "btn-floating btn-large waves-effect waves-light red" %><span class="brandColor btn-text">Add new record</span>
</div>
  <% @records.each do |record| %>
    <% unless record.status_title == "Deleted" %>
    <div class="col s12 m6">
      <h3 class="header text-center"><%= record.title %></h3>
      <div class="card horizontal">
        <div class="card-image">
          <!-- <img src="/assets/record-placeholder.jpeg"> -->
        </div>
        <div class="card-stacked">
          <div class="card-content">
            <p><%= record.content %></p>
            <p>How often: <%= record.frequency %></p>
            <p>Due: <%= record.due_date.strftime("%m %B %Y") %></p>
            <p>Category: <%= record.category.title %></p>
            <p>Status:
              <%= button_to "#{record.status_title}", update_status_record_path(record.id), :method => :post, :class => "waves-effect waves-light btn red"%>
            </p>
          </div>
          <div class="card-action">
            <div class="col s12 m6">
            <%= button_to "Edit", record_path(record.id),
:class => "waves-effect waves-light btn blue-grey darken-4
", :method => :get %>
            </div>
            <div class="col s12 m6">
            <%= button_to "Delete", record,
      :class => "waves-effect waves-light btn blue-grey darken-4
", :method => :delete, data: { confirm: 'Are you sure to delete this record?' } %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <% end %>
    <% end %>

app/views/records/_form.html.erb
  <%= form_for (@record) do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <%= f.label :desciption %>
    <%= f.text_area :content %>
    <%= f.label :category %>
    <div class="input-field">
    <%= f.select(:category_id, current_user.categories.all.map {|lc| [lc.title, lc.id]}, {prompt: 'Select Category'}) %>
    </div>
    <%= f.label :date %>
    <%= f.date_field :due_date %>

    <%= f.submit class: 'button radius'%>
  <% end %>

app/views/records/index.html.erb
  <div class="row" data-off-canvas-wrapper>

    <div class="small-2 columns left-column" data-off-canvas data-position="left">
      <div class="row column">
        <br>
        <h5>Categories</h5>
        <ul class="side-list">
          <% current_user.categories.all.each do |item| %>
            <li><%= link_to(item.title, category_path(item.id)) %>
          <% end %></li>
        </ul>
      </div>
      <%= link_to '+', new_category_path, :class => "btn-floating btn-large waves-effect waves-light red btn" %>

    </div>

    <div class="small-10 columns z-depth-3" data-off-canvas-content>
      <div class="title-bar hide-for-large">
        <div class="title-bar-left">
          <button class="menu-icon" type="button" data-open="my-info"></button>
        </div>
      </div>
      <div class="callout primary">
        <div class="row column">
          <div class="row">
           <div class="col s12">
              <%= render 'all_records' %>
            </div>
            <div class="col s12">
              <%= render 'all_categories' %>
            </div>
         </div>
        </div>
      </div>
    </div>
  </div>

app/views/records/new.html.erb
<div class="row column">
  <h1>Add</h1>
  <%= render 'form' %>
</div>

app/views/records/show.html.erb
<div class="row column">
  <h1>Edit</h1>
  <%= render 'form' %>
</div>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/contact.html.erb
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/static_pages/home.html.erb
<div class="callout large home-header">
  <div class="row column text-center">
    <h1>NZ Essential To-Do List</h1>
    <p class="lead z-depth-4">Where you keep all the document up to date.</p>
    <br>
    <a href="#" class="waves-effect waves-light btn-large default-btn">Getting Started</a>
    <% if user_signed_in? %>
      <%= link_to('Logout', destroy_user_session_path, :method => :delete, :class => "waves-effect waves-light btn-large default-btn") %>
    <% else %>
      <%= link_to('Login', new_user_session_path , :class => "waves-effect waves-light btn-large default-btn") %>
    <% end %>

    <% if user_signed_in? %>
      <%= link_to('Edit Profile', edit_user_registration_path, :class => "waves-effect waves-light btn-large default-btn") %>
    <% else %>
      <%= link_to('Register', new_user_registration_path, :class => "waves-effect waves-light btn-large default-btn")  %>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="medium-4 columns text-center">
    <h3>Health</h3>
    <img src="/assets/front-health.png">
    <p>Vivamus luctus urna sed urna ultricies ac tempor dui sagittis. In condimentum facilisis porta. Sed nec diam eu diam mattis viverra. Nulla fringilla, orci ac euismod semper, magna.</p>
  </div>
  <div class="medium-4 columns text-center">
    <h3>Car</h3>
    <img src="/assets/front-health.png">
    <p>Vivamus luctus urna sed urna ultricies ac tempor dui sagittis. In condimentum facilisis porta. Sed nec diam eu diam mattis viverra. Nulla fringilla, orci ac euismod semper, magna.</p>
  </div>
  <div class="medium-4 columns text-center">
    <h3>Property</h3>
    <img src="/assets/front-health.png">
    <p>Vivamus luctus urna sed urna ultricies ac tempor dui sagittis. In condimentum facilisis porta. Sed nec diam eu diam mattis viverra. Nulla fringilla, orci ac euismod semper, magna.</p>
  </div>
</div>

<% if user_signed_in? %>
<hr>
  <div class="row column">
    <h3>Your upcoming to-do</h3>
    <table class="centered">
      <thead>
        <tr>
          <th>Category</th>
          <th>Title</th>
          <th>Due Date</th>
          <th>Status</th>
        </tr>
      </thead>
        <tbody>
        <% current_user.records.all.each do |record| %>
          <% unless record.status_title == "Deleted" %>
          <tr>
            <td><%= record.category.title unless Record.last.category.nil? %></td>
            <td><%= record.title %></td>
            <td><%= record.due_date.strftime("Due on %m %B %Y") %></td>
            <td>
                <%= button_to "#{record.status_title}", update_status_record_path(record.id), :method => :post, :class => "waves-effect waves-light btn red"%>
            </td>
          </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>